name: Buildcontainers

# Refresh once a month.
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_images:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    # Set 6 hours timeout for the job
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - envoy_version: 1.31.0
            image: ghcr.io/mathetake/envoy-buildcontainer:v1.31-latest
            name: Debug build Envoy v1.31

    steps:
      - uses: actions/checkout@v4

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Frees up space # https://github.com/orgs/community/discussions/25678#discussioncomment-6533238
        run: rm -rf /opt/hostedtoolcache

      - name: Build ${{ matrix.image }}
        run: |
          docker build -f .github/workflows/Dockerfile.buildcontainer . -t ${{ matrix.image }} \
             --build-arg GIT_SHA_ARG=${{ github.sha }}

      - name: Push ${{ matrix.image }}
        run: docker push ${{ matrix.image }}
