name: Tests and Formats

on:
  pull_request:
    branches: [main]
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'
  push:
    branches: [main]
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'

concurrency:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (${{ matrix.envoy.name }})
    strategy:
      fail-fast: false
      matrix:
        envoy:
        - image: ghcr.io/envoyproxyx/envoyx-testcontainer:v1.30-latest
          name: Envoy 1.30

    defaults:
      run:
        working-directory: /build/envoyx

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.envoy.image }}
      options: --user vscode

    steps:
    - name: Checkout the commit.
      run: git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main && git checkout --detach ${{ github.sha }}

    - name: Run build
      run: bazel build //...

    - name: Run tests
      run: bazel test //...
