name: Tests and Format

on:
  pull_request:
    branches: [main]
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'
  push:
    branches: [main]
    paths-ignore:  # ignore docs as they are built with Netlify.
      - '**/*.md'

concurrency:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  test:
    name: Build & Test on Envoy v${{ matrix.envoy.version }}
    strategy:
      fail-fast: false
      matrix:
        envoy:
        # Build images are built by the buildcontainers workflow.
        - image: ghcr.io/envoyproxyx/envoyx-buildcontainer:v1.30-latest
          # The tag of the Envoy image to build the final image.
          envoy_image_tag: v1.30-latest
          version: 1.30.4
        - image: ghcr.io/envoyproxyx/envoyx-buildcontainer:v1.29-latest
          # The tag of the Envoy image to build the final image.
          envoy_image_tag: v1.29-latest
          version: 1.29.7

    runs-on: ubuntu-latest
    steps:
    - name: Frees up space # https://github.com/orgs/community/discussions/25678#discussioncomment-6533238
      run: rm -rf /opt/hostedtoolcache

    - uses: actions/checkout@v3

    # To extract the Envoy binary from the buildcontainer, we run docker run in a single step.
    - name: Run tests
      run: |
        mkdir -p /tmp/gha
        docker run --user envoyxbuild -v $(pwd):/tmp/gha ${{ matrix.envoy.image }} /bin/bash -c "\
          git reset --hard && \
          git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main && \
          git checkout --detach ${{ github.sha }} && \
          sed -i 's/ENVOY_VERSION\s=\s.*/ENVOY_VERSION=\"${{ matrix.envoy.version }}\"/' bazel/repositories.bzl && \
          bazel build //... && \
          bazel test //... && \
          sudo cp bazel-bin/envoy /tmp/gha/envoy"

    - name: Check Envoy binary
      run: |
        file ./envoy
        ./envoy --version

    - name: Login into GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push ghcr.io/envoyproxyx/envoyx:${{ matrix.envoy.envoy_image_tag }}-${{ github.sha }}
      if: github.event_name == 'push'
      run: |
        IMAGE=ghcr.io/envoyproxyx/envoyx:${{ matrix.envoy.envoy_image_tag }}-${{ github.sha }}
        docker build -f .github/workflows/Dockerfile.envoy . \
            -t $IMAGE --build-arg ENVOY_IMAGE_TAG=${{ matrix.envoy.envoy_image_tag }}
        docker push $IMAGE
